name: loan_system

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env.docker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
      # - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - loan_network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=200
      --innodb_buffer_pool_size=256M
      --innodb_log_file_size=64M
      --slow_query_log=1
      --slow_query_log_file=/var/log/mysql/slow.log
      --long_query_time=2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - loan_network

  alloy:
    image: grafana/alloy:v1.9.2
    container_name: alloy
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.docker
    command: >
      run 
      --server.http.listen-addr=0.0.0.0:12345 
      --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy
    restart: unless-stopped
    networks:
      - loan_network

volumes:
  mysql_data:
    driver: local

networks:
  loan_network:
    driver: bridge
